### ISSUE TITLE
preserveObjectReferences can result in InvalidCastException

### ISSUE THREAD

**Issue by zbynek001** [akkadotnet/Hyperion#96] opened 2018-05-21 18:11 UTC
when `Uri` is serialized with preserveObjectReferences and versionTolerance enabled, deserialization will fail with `InvalidCastException`.

It happens like this. During serialization,
- SerializerSession will track `Uri` itself
- `Uri` contains the url itself in several fields as string
- it'll try to serialize the `string` value
- `session.TryGetObjectId` will find the previous object, unfortunatelly it won't be `string`, but `Uri`
- Later, during deserialization, this will result in `InvalidCastException`

Reason is, that `SerializerSession` is using default equality comparer for tracked objects and `string` and `Uri` are equal, when having the same value.

**Comment by Horusiath** [comment] 2018-05-21 20:34
Possible duplicate of #85 ?

**Comment by zbynek001** [comment] 2018-05-22 08:01
Not sure, but I'd say it's not the same issue

**Closed** 2018-10-25 21:30 UTC
Labels: bug
